name: Update Credly Badges

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Update Credly Badges
        uses: jd-35656/readme-credly-badges@v1
        with:
          credly_username: "kimrakji"
          badge_size: "80x80"
          badge_sort_by: "issued"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: "chore: update Credly badges"
